### PR TITLE
Making sure that when the keyboard is dismissed the former tableView contentInsets are restored.

### PR DESCRIPTION
**Pull request by gtranchedone**

### CODE REVIEW

**Comment by markst** [comment]
This is pretty buggy on iOS9. 
Also an issue if `UIKeyboardWillHideNotification` gets could get called before `UIKeyboardDidShowNotification`. i.e If a modal view is presented with a `FXForm` & the vc behind the modal has a keyboard input which is resigned...

**Comment by gtranchedone** [comment]
I'll try to have a look at it by this weekend. In the mean time, do you have a code sample showing the issue?

**Comment by markst** [comment]
@gtranchedone not really. but issue occurs for me even when pushing a vc with a `FXForm`. Seems like an iOS9 thing where by `UIKeyboardWillHideNotification` is called more than balanced show... 
http://stackoverflow.com/questions/32860151/uikeyboardwillshownotification-calling-twice-ios-9

**Comment by markst** [comment]
Could KVO the content insets? or just expose the property `originalTableContentInset` which isn't set by the `keyboardDidShow:`.

**Pull request merged**
