### PR TITLE
Carry cell configuration through to Options

### PR DESCRIPTION
**Pull request by ohwutup**
This pull request just makes sure that when using an option picker, that the view controller which displays the options uses the same cell configuration as the cell which had been tapped.

See: https://github.com/nicklockwood/FXForms/issues/149

### CODE REVIEW

**Comment by aryaxt** [comment]
Hey guys. What version did this go into? I'm not seeing this behavior in 1.2.12

**Comment by ohwutup** [comment]
@aryaxt - im not exactly sure, but it looks like 1.2.13 is the most recent version @nicklockwood  has released.

**Comment by aryaxt** [comment]
Hmmm looks like it was merged to master, but not released. 
@nicklockwood any reason why those changes weren't included? any plan on releasing a new version with those changes anytime soon?

Thanks

**Comment by ohwutup** [comment]
if you point your podfile to master of this pod you'll get it

**Comment by aryaxt** [comment]
@ohwutup  thanks, yep but I wanna know if there was a reason why it was not included in a version that was released after the PR was merged. Just being cautious :)

**Comment by nicklockwood** [comment]
@aryaxt I'm not sure I understand the question. It's included in version 1.2.13, which is the latest version on CocoaPods. It's not included in 1.2.12 because that version was released before that feature was merged.

**Comment by aryaxt** [comment]
My bad, I looked at the wrong commit. I updated to 1.2.13 and everything works great thanks

**Pull request merged**
